# Tratamento de Exce√ß√µes em Kotlin
```
Bootcamp Code Update TQI Back End com Java e Kotlin
M√≥dulo: Desmistificando Kotlin para programadores Java
Instrutor: Venilton Falvo Jr. @falvojr - 29/08/23 a 29/10/23
```

## Apresenta√ß√£o

Como lidar com eventuais erros que ocorrem no dia-a-dia de todo programador √© o escopo dessa unidade. Ser√° fornecido um conjunto de informa√ß√µes que possibilitar√° o melhor entendimento e a busca de solu√ß√µes para cada tipo de exception.

## Nivelamento

Exce√ß√µes em linguagens de programa√ß√£o, muitas vezes chamadas de "exce√ß√µes" ou "erros de exce√ß√£o", s√£o eventos ou condi√ß√µes anormais que ocorrem durante a execu√ß√£o de um programa. 

Elas indicam situa√ß√µes inesperadas ou inadequadas que podem interromper o fluxo normal de execu√ß√£o de um programa. Quando uma exce√ß√£o ocorre, a linguagem de programa√ß√£o fornece mecanismos para capturar, tratar e, em alguns casos, relatar essas exce√ß√µes.

Aqui est√£o alguns conceitos-chave relacionados a exce√ß√µes:

**Causas de Exce√ß√µes**: As exce√ß√µes podem ser causadas por diversos motivos, como divis√£o por zero, acesso a um √≠ndice fora dos limites de um array, tentativa de abrir um arquivo inexistente, entre outros. Elas s√£o geralmente erros ou condi√ß√µes n√£o previstos durante a codifica√ß√£o.

**Captura de Exce√ß√µes**: Para lidar com exce√ß√µes, as linguagens de programa√ß√£o oferecem estruturas de controle, como blocos "try-catch" (ou "try-except" em algumas linguagens). Quando um bloco "try" √© executado, o programa monitora se ocorre uma exce√ß√£o. Se ocorrer, o bloco "catch" correspondente √© executado para tratar a exce√ß√£o.

**Tratamento de Exce√ß√µes**: O tratamento de exce√ß√µes envolve tomar medidas apropriadas para lidar com a exce√ß√£o. Isso pode incluir registrar o erro, exibir uma mensagem de erro para o usu√°rio, tentar uma a√ß√£o alternativa ou encerrar o programa de forma controlada.

**Propaga√ß√£o de Exce√ß√µes**: Em alguns casos, √© poss√≠vel propagar (lan√ßar) exce√ß√µes para um n√≠vel superior na hierarquia de chamadas de fun√ß√£o. Isso permite que partes diferentes do c√≥digo lidem com a mesma exce√ß√£o de maneira adequada ao contexto.

**Exce√ß√µes Personalizadas**: Al√©m das exce√ß√µes predefinidas pela linguagem, os programadores podem criar suas pr√≥prias exce√ß√µes personalizadas para representar erros espec√≠ficos do dom√≠nio de aplica√ß√£o.

**Exce√ß√µes N√£o Tratadas**: Se uma exce√ß√£o n√£o for tratada (ou seja, n√£o for capturada por um bloco "try-catch" apropriado), ela geralmente levar√° √† interrup√ß√£o do programa e pode gerar mensagens de erro n√£o controladas.

### Objetivos

- Compreender o funcionamento das Exceptions em Kotlin
- Compreender as pilhas de exce√ß√£o do Kotlin
- [Link da documenta√ß√£o oficial sobre Exceptions](https://kotlinlang.org/docs/exceptions.html)

### Introdu√ß√£o

Todas as classes de exce√ß√£o em Kotlin herdam a classe `Throwable`. Cada exce√ß√£o possui uma mensagem, um rastreamento de pilha e uma causa opcional.

Para lan√ßar um objeto de exce√ß√£o, use a express√£o `throw`:

```kotlin
fun main() {
    throw Exception("Hi There!")
}
```
**Sa√≠da do c√≥digo**

```
Exception in thread "main" java.lang.Exception: Hi There!
 at FileKt.main (File.kt:2) 
 at FileKt.main (File.kt:-1) 
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (:-2) 
```


### Manipulando as primeiras exce√ß√µes


Para capturar uma exce√ß√£o, use a express√£o try...catch:

```kotlin
try {
    // some code
} catch (e: SomeException) {
    // handler
} finally {
    // optional finally block
}
```
Exemplo: 
```kotlin
fun main() {

    val a = 10
    val b = 0
    
    try {
        val divisao = a/b
    } catch (e: ArithmeticException){
        println ("Erro de divis√£o por zero")
    } catch(e: Throwable) {
        //e.printStackTrace()  (imprime a pilha de exception )
        println(e.message)
    } finally {
        println("Esse bloco √© opcional")
    }
}
```

Pode haver zero ou mais blocos catch e o bloco final pode ser omitido (finally). No entanto, pelo menos um bloco `catch` ou `finally` √© necess√°rio.


‚ö† O bloco `finally`, caso exista, __sempre__ ser√° executado.

### Try √© uma expression

try √© uma express√£o, o que significa que pode ter um valor de retorno:

```kotlin
val a: Int? = try { input.toInt() } catch (e: NumberFormatException) { null }
```
üëç Pelo exemplo vemos que √© poss√≠vel usar try..catch para uma vari√°vel.

No exemplo acima para a vari√°vel imut√°vel `a` declarada como Int com possibilidade de receber `null` √© feita a tentativa (try) de convers√£o para inteiro e caso se receba uma exce√ß√£o do tipo `NumberFormatException` a vari√°vel receber√° `null`.

O valor retornado de uma express√£o `try` √© a √∫ltima express√£o no bloco try ou a √∫ltima express√£o no bloco `catch` (ou blocos). O conte√∫do do bloco `finally` n√£o afeta o resultado da express√£o.

Usando o exemplo anteriormente criado:

```kotlin
fun main() {

    val a = 10
    val b = 0
    
    // usando uma try expression aplicada a uma atribui√ß√£o de vari√°vel
    val divisao = try {a/b} catch (e: ArithmeticException) {"Divis√£o por zero. Null atribu√≠do"}
    println(divisao)  
}
```
**Sa√≠da do c√≥digo**

```
Divis√£o por zero. Null atribu√≠do
```

### Checked Exceptions

Em Java, "checked exceptions" (exce√ß√µes verificadas) s√£o um tipo de exce√ß√£o que o compilador exige que voc√™ trate explicitamente em seu c√≥digo. Essas exce√ß√µes s√£o verificadas pelo compilador durante o tempo de compila√ß√£o e, se voc√™ n√£o as tratar corretamente, seu c√≥digo n√£o ser√° compilado com sucesso.

![Checked Exceptions in Java](.img/checkedException.PNG)

Kotlin `n√£o` possui exce√ß√µes verificadas (checked exceptions). 

Assim o desenvolvedor n√£o est√° obrigado a tratar nenhuma exception embora seja desej√°vel analisar cada caso.

Kotlin, sendo interoper√°vel com Java, permite a utiliza√ß√£o e o tratamento de qualquer exce√ß√£o originada do Java, incluindo a IOException.

O Kotlin n√£o diferencia entre exce√ß√µes checked e unchecked, um conceito presente em Java. Isso significa que, enquanto no Java voc√™ √© obrigado a tratar ou declarar uma exce√ß√£o checked, em Kotlin isso n√£o √© uma exig√™ncia. 

Entretanto, ainda √© poss√≠vel e muitas vezes recomendado tratar essas exce√ß√µes para evitar crashes inesperados e garantir que seu c√≥digo seja seguro e est√°vel.

Aqui est√° um exemplo de como voc√™ pode tratar uma IOException em Kotlin:

```kotlin
import java.io.IOException

fun main() {
    try {
        // O c√≥digo que pode lan√ßar uma IOException vai aqui
    } catch (e: IOException) {
        // Trate a IOException aqui println("Ocorreu uma IOException: ${e.message}")
    }
}
```

### Exce√ß√µes customizadas e idiom√°ticas

```kotlin
fun vote (name: String, age: Int) {
    if (age < 16) {
        throw IllegalArgumentException("Apenas maiores de 16 anos podem votar")
    }
    println("Voto de $name realizado com sucesso)
}

fun main() {
    vote("Venilton", 33)
}
```
A documenta√ß√£o sugere que se utilize `annotations` para indicar a necessidade de tratamento de `exceptions`, como abaixo exemplificado, onde foi criada uma classe `IllegalVoterException` para tratar especificamente a `exception`.

```kotlin
class IllegalVoterException (message: String) : Throwable(message)

@Throws(IllegalVoterException::class)  // Exception customizada
fun vote (name: String, age: Int) {
    if (age < 16) {
        throw IllegalVoterException("Apenas maiores de 16 anos podem votar")
    }
    println("Voto de $name realizado com sucesso)
}

fun main() {
    vote("Venilton", 33)
    vote("Maria", 14)
    vote("Renan", 50)
}
```
Outra possibilidade seria tratar a exceptio com try..catch:

```kotlin
class IllegalVoterException (message: String) : Throwable(message)

@Throws(IllegalVoterException::class)  // Exception customizada
fun vote (name: String, age: Int) {
    if (age < 16) {
        throw IllegalVoterException("Apenas maiores de 16 anos podem votar")
    }
    println("Voto de $name realizado com sucesso")
}

fun main() {
    var quantidadeVotos = 0
    quantidadeVotos += try {vote("Venilton", 33); 1; } catch (e: IllegalVoterException) {0}
    quantidadeVotos += try {vote("Maria", 14); 1; } catch (e: IllegalVoterException) {0}
    quantidadeVotos += try {vote("Renan", 50); 1; } catch (e: IllegalVoterException) {0}
    println("Total de votos apurados: $quantidadeVotos")
}
```
**Sa√≠da do c√≥digo**

```
Voto de Venilton realizado com sucesso
Voto de Renan realizado com sucesso
Total de votos apurados: 2
```

### Throw √© uma Expression, Tipo Nothing e Conclus√£o

Asim como o `try`, o `throw` tamb√©m √© uma `expression`. Sendo assim voc√™ pode us√°-la, por exemplo, como parte de uma express√£o de Elvis:

```kotlin
val s = person.name ?: throw IllegalArgumentException("Name required")
```
A express√£o `throw` tem o tipo `Nothing`. Este tipo n√£o possui valores e √© usado para marcar locais de c√≥digo que nunca podem ser alcan√ßados. No seu pr√≥prio c√≥digo, voc√™ pode usar `Nothing` para marcar uma fun√ß√£o que nunca retorna.


## Conclus√£o

Nesse m√≥dulo foram apresentados os principais t√≥picos referentes √†s Exce√ß√µes em Kotlin.

Inicialmente foi apresentado a classe Throwable respons√°vel no Kotlin por lan√ßar um exce√ß√£o ou `exception`. 

Para tratamento das `exceptions` o Kotlin utiliza o recurso de `try..catch..finally` com algumas particularidades como a possibilidade de us√°-lo como express√µes, podendo ser aplicado at√© mesmo a uma vari√°vel.

Uma discuss√£o sobre a obrigat√≥riedade de se tratar exce√ß√µes contrapondo algumas linguagens que a utilizam como o Java, foi conduzida de forma a criar uma base de refer√™ncia importante para argumenta√ß√£o ante a n√£o-obrigatoriedade desse recurso no Kotlin, demonstrando a import√¢ncia de se atribuir aos desenvolvedores o papel de adequar o c√≥digo √† real necessidade de cada modelo de neg√≥cio.

Finalmente foi apresentado um exemplo pr√°tico de utiliza√ß√£o das Exceptions e seu tratamento customizado.

Como trata-se de um tema importante e tamb√©m muito complexo uma vez que exige uma viv√™ncia com o desenvolvimento de c√≥digo para melhor aproveitamento do treinamento, n√£o foi poss√≠vel uma assimila√ß√£o mais aprofundada do conte√∫do.

Mesmo com essas exig√™ncias o Instrutor Venilton Falvo Jr @falvojr conseguiu brilhantemente elucidar e esclarecer as principais quest√µes relativas ao t√≥pico, principalmente na cria√ß√£o de um c√≥digo pr√°tico de exemplo, fora da documenta√ß√£o oficial do Kotlin.

## Materiais de apoio e refer√™ncias

[Reposit√≥rio da DIO](https://github.com/digitalinnovationone/aprenda-kotlin-com-exemplos)

[Documenta√ß√£o oficial do Kotlin](https://kotlinlang.org/)

[Ferramenta de Intelig√™ncia artificial ChatGPT](https://chat.openai.com/)

[Ferramenta de Intelig√™ncia artificial AI Converter](https://aicodeconvert.com/)

## Certificado

![Certificado](../img/m3-certificadoTratamentoExcecoesKotlin.png)

```
Disclaimer:

Todo o material aqui apresentado foi gerado a partir de minhas anota√ß√µes de aula durante o excelente
treinamento ministrado  pelo Instrutor Venilton Falvo Jr. @falvojr. Proibida a reprodu√ß√£o e veicula√ß√£o
sem a ci√™ncia e autoriza√ß√£o da DIO e do autor.
```